import { useEffect, useState, type FormEvent } from 'react'
import { Landmark, Plus, RefreshCw, ArrowDownLeft, ArrowUpRight, ClipboardCheck } from 'lucide-react'
import { NavBar } from '../components/NavBar'
import { useOrganization } from '../context/OrganizationContext'
import { fetchProjects, type Project } from '../services/projects'
import { formatDate } from '../utils/date'
import { createBankAccount, createBankTransaction, fetchBankAccounts, fetchBankReconciliations, fetchBankTransactions, reconcileBank, type BankAccount, type BankReconciliation, type BankTransaction } from '../services/bank'

const today = new Date().toISOString().slice(0, 10)
const money = (v: string|number, c: string) => `${Number(v).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})} ${c}`
const msg = (e:any, fallback:string) => e?.response?.data?.message ?? fallback

export default function Bank() {
  const { currentOrganization } = useOrganization()
  const [accounts,setAccounts]=useState<BankAccount[]>([]), [selectedId,setSelectedId]=useState(''), [transactions,setTransactions]=useState<BankTransaction[]>([]), [reconciliations,setReconciliations]=useState<BankReconciliation[]>([]), [projects,setProjects]=useState<Project[]>([])
  const [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [refreshing,setRefreshing]=useState(false), [error,setError]=useState<string|null>(null)
  const [modal,setModal]=useState<'account'|'transaction'|'reconcile'|null>(null)
  const [account,setAccount]=useState({code:'',name:'',bank_name:'',account_number:'',currency:'XOF',opening_balance:0})
  const [transaction,setTransaction]=useState({type:'in' as 'in'|'out',amount:0,transaction_date:today,reference:'',description:'',project_id:''})
  const [reconcile,setReconcile]=useState({reconciliation_date:today,statement_balance:0,notes:''})
  const selected=accounts.find(a=>a.id===selectedId)

  async function load(preferred?:string){ if(!currentOrganization)return; setLoading(true);setError(null);try{const [a,p]=await Promise.all([fetchBankAccounts(currentOrganization.id),fetchProjects(currentOrganization.id)]);setAccounts(a);setProjects(p);const id=preferred&&a.some(x=>x.id===preferred)?preferred:a[0]?.id??'';setSelectedId(id);if(id){const [t,r]=await Promise.all([fetchBankTransactions(currentOrganization.id,id),fetchBankReconciliations(currentOrganization.id,id)]);setTransactions(t);setReconciliations(r)}else{setTransactions([]);setReconciliations([])}}catch(e){setError(msg(e,'Impossible de charger les données bancaires.'))}finally{setLoading(false)}}
  useEffect(()=>{load()},[currentOrganization?.id])
  useEffect(()=>{if(!loading&&selectedId&&currentOrganization){Promise.all([fetchBankTransactions(currentOrganization.id,selectedId),fetchBankReconciliations(currentOrganization.id,selectedId)]).then(([t,r])=>{setTransactions(t);setReconciliations(r)}).catch(e=>setError(msg(e,'Impossible de charger le compte.'))) }},[selectedId])
  const refresh=async()=>{setRefreshing(true);try{await load(selectedId)}finally{setRefreshing(false)}}
  async function saveAccount(e:FormEvent){e.preventDefault();if(!currentOrganization)return;setSaving(true);try{const a=await createBankAccount(currentOrganization.id,{...account,currency:account.currency.toUpperCase()});setModal(null);setAccount({code:'',name:'',bank_name:'',account_number:'',currency:currentOrganization.default_currency??'XOF',opening_balance:0});await load(a.id)}catch(e){setError(msg(e,'Impossible de créer le compte bancaire.'))}finally{setSaving(false)}}
  async function saveTransaction(e:FormEvent){e.preventDefault();if(!currentOrganization||!selected)return;setSaving(true);try{await createBankTransaction(currentOrganization.id,selected.id,{...transaction,project_id:transaction.project_id||null});setModal(null);await load(selected.id)}catch(e){setError(msg(e,'Impossible d’enregistrer le mouvement.'))}finally{setSaving(false)}}
  async function saveReconcile(e:FormEvent){e.preventDefault();if(!currentOrganization||!selected)return;setSaving(true);try{await reconcileBank(currentOrganization.id,selected.id,reconcile);setModal(null);await load(selected.id)}catch(e){setError(msg(e,'Impossible d’enregistrer le rapprochement.'))}finally{setSaving(false)}}

  return <div className="min-h-screen bg-slate-50"><NavBar/><main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8"><header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-slate-500">FINANCES</p><h1 className="mt-1 text-2xl font-semibold text-slate-950">Banque</h1><p className="mt-1 text-sm text-slate-500">Comptes, mouvements et rapprochement bancaire.</p></div><div className="flex gap-2"><button onClick={refresh} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><RefreshCw size={16} className={refreshing?'inline animate-spin':'inline'}/> Actualiser</button><button onClick={()=>setModal('account')} className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white"><Plus size={16} className="mr-1 inline"/>Nouveau compte</button></div></header>
  {error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
  {loading?<Panel text="Chargement des comptes bancaires…"/>:accounts.length===0?<Panel text="Aucun compte bancaire configuré."><button onClick={()=>setModal('account')} className="mt-4 rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Créer le premier compte</button></Panel>:<>
  <div className="mb-5 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100"><Landmark size={20}/></div><div><p className="text-xs uppercase tracking-wide text-slate-400">Compte sélectionné</p><p className="font-semibold">{selected?.name}</p></div></div><select value={selectedId} onChange={e=>setSelectedId(e.target.value)} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm">{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Solde comptable" value={money(selected?.current_balance??0,selected?.currency??'XOF')}/><Stat label="Entrées" value={money(transactions.filter(t=>t.type==='in').reduce((s,t)=>s+Number(t.amount),0),selected?.currency??'XOF')} icon={<ArrowDownLeft size={18}/>}/><Stat label="Sorties" value={money(transactions.filter(t=>t.type==='out').reduce((s,t)=>s+Number(t.amount),0),selected?.currency??'XOF')} icon={<ArrowUpRight size={18}/>}/><Stat label="Dernier écart" value={reconciliations[0]?money(reconciliations[0].difference,selected?.currency??'XOF'):'—'} icon={<ClipboardCheck size={18}/>}/></div>
  <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_360px]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-semibold">Mouvements bancaires</h2><p className="mt-1 text-xs text-slate-500">Entrées et sorties validées.</p></div><button disabled={selected?.status!=='open'} onClick={()=>setModal('transaction')} className="rounded-lg bg-slate-950 px-3 py-2 text-sm font-semibold text-white disabled:opacity-40"><Plus size={16} className="mr-1 inline"/>Mouvement</button></div>{transactions.length===0?<div className="p-8 text-center text-sm text-slate-400">Aucun mouvement enregistré.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-400"><tr><th className="px-5 py-3">Date</th><th className="px-5 py-3">Nature</th><th className="px-5 py-3">Description</th><th className="px-5 py-3">Projet</th><th className="px-5 py-3 text-right">Montant</th></tr></thead><tbody>{transactions.map(t=><tr key={t.id} className="border-t border-slate-100"><td className="px-5 py-3">{formatDate(t.transaction_date)}</td><td className="px-5 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${t.type==='in'?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>{t.type==='in'?'Entrée':'Sortie'}</span></td><td className="px-5 py-3">{t.description||t.reference||'—'}</td><td className="px-5 py-3 text-slate-500">{t.project?.name??'—'}</td><td className="px-5 py-3 text-right font-semibold">{t.type==='in'?'+':'−'}{money(t.amount,selected?.currency??'XOF')}</td></tr>)}</tbody></table></div>}</section><aside className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Rapprochement bancaire</h2><p className="mt-1 text-xs text-slate-500">Solde comptable contre relevé bancaire.</p><button onClick={()=>{setReconcile({reconciliation_date:today,statement_balance:Number(selected?.current_balance??0),notes:''});setModal('reconcile')}} className="mt-4 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold">Nouveau rapprochement</button>{reconciliations[0]&&<div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm"><div className="flex justify-between"><span>Solde relevé</span><b>{money(reconciliations[0].statement_balance,selected?.currency??'XOF')}</b></div><div className="mt-2 flex justify-between"><span>Écart</span><b>{money(reconciliations[0].difference,selected?.currency??'XOF')}</b></div></div>}</aside></div></>}
  {modal==='account'&&<Modal title="Nouveau compte bancaire" close={()=>setModal(null)}><form onSubmit={saveAccount} className="space-y-3"><Input label="Code" required value={account.code} onChange={v=>setAccount({...account,code:v})}/><Input label="Nom du compte" required value={account.name} onChange={v=>setAccount({...account,name:v})}/><Input label="Banque" required value={account.bank_name} onChange={v=>setAccount({...account,bank_name:v})}/><Input label="Numéro de compte" value={account.account_number} onChange={v=>setAccount({...account,account_number:v})}/><div className="grid grid-cols-2 gap-3"><Input label="Devise" required value={account.currency} onChange={v=>setAccount({...account,currency:v})}/><Input label="Solde initial" type="number" required value={account.opening_balance} onChange={v=>setAccount({...account,opening_balance:Number(v)})}/></div><Submit saving={saving}/></form></Modal>}
  {modal==='transaction'&&<Modal title="Nouveau mouvement" close={()=>setModal(null)}><form onSubmit={saveTransaction} className="space-y-3"><Select label="Nature" value={transaction.type} onChange={v=>setTransaction({...transaction,type:v as 'in'|'out'})} options={[['in','Entrée'],['out','Sortie']]}/><Input label="Montant" type="number" required value={transaction.amount} onChange={v=>setTransaction({...transaction,amount:Number(v)})}/><Input label="Date" type="date" required value={transaction.transaction_date} onChange={v=>setTransaction({...transaction,transaction_date:v})}/><Input label="Référence" value={transaction.reference} onChange={v=>setTransaction({...transaction,reference:v})}/><Input label="Description" value={transaction.description} onChange={v=>setTransaction({...transaction,description:v})}/><Select label="Projet" value={transaction.project_id} onChange={v=>setTransaction({...transaction,project_id:v})} options={[['','Aucun'],...projects.map(p=>[p.id,p.name])]}/><Submit saving={saving}/></form></Modal>}
  {modal==='reconcile'&&<Modal title="Rapprochement bancaire" close={()=>setModal(null)}><form onSubmit={saveReconcile} className="space-y-3"><Input label="Date du relevé" type="date" required value={reconcile.reconciliation_date} onChange={v=>setReconcile({...reconcile,reconciliation_date:v})}/><Input label="Solde du relevé" type="number" required value={reconcile.statement_balance} onChange={v=>setReconcile({...reconcile,statement_balance:Number(v)})}/><Input label="Notes" value={reconcile.notes} onChange={v=>setReconcile({...reconcile,notes:v})}/><Submit saving={saving}/></form></Modal>}</main></div>
}
function Stat({label,value,icon}:{label:string;value:string;icon?:React.ReactNode}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-xs text-slate-500">{icon}{label}</div><div className="mt-2 text-xl font-semibold">{value}</div></div>}
function Panel({text,children}:{text:string;children?:React.ReactNode}){return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><Landmark className="mx-auto text-slate-400"/><p className="mt-3 text-sm text-slate-500">{text}</p>{children}</div>}
function Input({label,value,onChange,type='text',required=false}:{label:string;value:any;onChange:(v:string)=>void;type?:string;required?:boolean}){return <label className="block text-sm"><span className="mb-1 block font-medium text-slate-700">{label}</span><input required={required} type={type} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-slate-200 px-3 py-2 outline-none focus:border-slate-400"/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[][]}){return <label className="block text-sm"><span className="mb-1 block font-medium text-slate-700">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-slate-200 px-3 py-2">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/30 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl"><div className="mb-4 flex justify-between"><h2 className="font-semibold">{title}</h2><button type="button" onClick={close} className="text-xl text-slate-400">×</button></div>{children}</div></div>}
function Submit({saving}:{saving:boolean}){return <button disabled={saving} className="w-full rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?'Enregistrement…':'Enregistrer'}</button>}
